# Removed currently cuz im realizing im slamming their websites with scraping every 2 hours
# Will add updated more efficient workflows and scrape.js which would only do like 2req/s for deep scans (ran every 2 days?)
# and would mark series with dropped n all to reduce the fetch requests... demonicscans.org has >13k fetch requests sent every 2 hours with the implementation...
# thats not supporting scanlations, that destroying them...
